spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chargebuddy
    username: root
    password: skawjdgus0114@@


  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true



    springdoc:
      api-docs:
        path: /api-docs
      swagger-ui:
        path: /swagger-ui.html