spring:
  application:
    name: ChargeBuddy

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

  config:
    import: optional:file:.env[.properties] # .env import

  datasource:
    url: jdbc:mysql://chargebuddy-database.cveu4wmoivfs.ap-northeast-2.rds.amazonaws.com:3306/chargebuddy  # ${DB_URL}
    username: ${DB_ID}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect


custom:
  api:
    serviceKey: ${SERVICE_KEY}
    reviewKey: ${REVIEW_KEY}
    localKey: ${LOCAL_KEY}
    summeryKey: ${SUMMERY_KEY}