spring:
  application:
    name: ChargeBuddy

  batch:
    job:
      enabled: false

  config:
    import: optional:file:.env[.properties]

  datasource:
    url : ${DB_URL}
    username: ${DB_ID}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

custom:
  api:
    serviceKey: ${service_key}
    reviewKey: ${review_key}
    localKey: ${local_key}
    summeryKey: ${summery_Key}